---
- name: Update packages on all servers
  hosts: servers
  become: true
  tasks:
    - name: Update packages
      apt:
        upgrade: yes

- name: Docker init
  hosts: servers
  become: true
  tasks:
    - name: Install deps
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - docker-compose
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: present

- name: Start Docker containers on all servers
  hosts: servers
  become: true
  tasks:
    - name: Copy Docker files to all servers
      copy:
        src: ./docker
        dest: /home/rob
    - name: Start Docker containers
      command: docker-compose up -d
      args:
        chdir: /home/rob/docker
